// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin_demo/internal/model"
)

func newCaptchaCode(db *gorm.DB, opts ...gen.DOOption) captchaCode {
	_captchaCode := captchaCode{}

	_captchaCode.captchaCodeDo.UseDB(db, opts...)
	_captchaCode.captchaCodeDo.UseModel(&model.CaptchaCode{})

	tableName := _captchaCode.captchaCodeDo.TableName()
	_captchaCode.ALL = field.NewAsterisk(tableName)
	_captchaCode.ID = field.NewUint64(tableName, "id")
	_captchaCode.CaptchaType = field.NewInt64(tableName, "captcha_type")
	_captchaCode.CaptchaAccount = field.NewString(tableName, "captcha_account")
	_captchaCode.CaptchaCode = field.NewString(tableName, "captcha_code")
	_captchaCode.IsExpired = field.NewUint64(tableName, "is_expired")
	_captchaCode.IsUsed = field.NewInt64(tableName, "is_used")
	_captchaCode.ExpiredTime = field.NewInt64(tableName, "expired_time")
	_captchaCode.CreatedAt = field.NewUint64(tableName, "created_at")
	_captchaCode.UpdatedAt = field.NewUint64(tableName, "updated_at")

	_captchaCode.fillFieldMap()

	return _captchaCode
}

type captchaCode struct {
	captchaCodeDo

	ALL            field.Asterisk
	ID             field.Uint64
	CaptchaType    field.Int64 // 1 mobile 2 email
	CaptchaAccount field.String
	CaptchaCode    field.String
	IsExpired      field.Uint64 // 1：未过期  2：已失效
	IsUsed         field.Int64  // 1：已使用  0：未使用
	ExpiredTime    field.Int64
	CreatedAt      field.Uint64
	UpdatedAt      field.Uint64

	fieldMap map[string]field.Expr
}

func (c captchaCode) Table(newTableName string) *captchaCode {
	c.captchaCodeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c captchaCode) As(alias string) *captchaCode {
	c.captchaCodeDo.DO = *(c.captchaCodeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *captchaCode) updateTableName(table string) *captchaCode {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CaptchaType = field.NewInt64(table, "captcha_type")
	c.CaptchaAccount = field.NewString(table, "captcha_account")
	c.CaptchaCode = field.NewString(table, "captcha_code")
	c.IsExpired = field.NewUint64(table, "is_expired")
	c.IsUsed = field.NewInt64(table, "is_used")
	c.ExpiredTime = field.NewInt64(table, "expired_time")
	c.CreatedAt = field.NewUint64(table, "created_at")
	c.UpdatedAt = field.NewUint64(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *captchaCode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *captchaCode) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["captcha_type"] = c.CaptchaType
	c.fieldMap["captcha_account"] = c.CaptchaAccount
	c.fieldMap["captcha_code"] = c.CaptchaCode
	c.fieldMap["is_expired"] = c.IsExpired
	c.fieldMap["is_used"] = c.IsUsed
	c.fieldMap["expired_time"] = c.ExpiredTime
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c captchaCode) clone(db *gorm.DB) captchaCode {
	c.captchaCodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c captchaCode) replaceDB(db *gorm.DB) captchaCode {
	c.captchaCodeDo.ReplaceDB(db)
	return c
}

type captchaCodeDo struct{ gen.DO }

type ICaptchaCodeDo interface {
	gen.SubQuery
	Debug() ICaptchaCodeDo
	WithContext(ctx context.Context) ICaptchaCodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICaptchaCodeDo
	WriteDB() ICaptchaCodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICaptchaCodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICaptchaCodeDo
	Not(conds ...gen.Condition) ICaptchaCodeDo
	Or(conds ...gen.Condition) ICaptchaCodeDo
	Select(conds ...field.Expr) ICaptchaCodeDo
	Where(conds ...gen.Condition) ICaptchaCodeDo
	Order(conds ...field.Expr) ICaptchaCodeDo
	Distinct(cols ...field.Expr) ICaptchaCodeDo
	Omit(cols ...field.Expr) ICaptchaCodeDo
	Join(table schema.Tabler, on ...field.Expr) ICaptchaCodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICaptchaCodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICaptchaCodeDo
	Group(cols ...field.Expr) ICaptchaCodeDo
	Having(conds ...gen.Condition) ICaptchaCodeDo
	Limit(limit int) ICaptchaCodeDo
	Offset(offset int) ICaptchaCodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICaptchaCodeDo
	Unscoped() ICaptchaCodeDo
	Create(values ...*model.CaptchaCode) error
	CreateInBatches(values []*model.CaptchaCode, batchSize int) error
	Save(values ...*model.CaptchaCode) error
	First() (*model.CaptchaCode, error)
	Take() (*model.CaptchaCode, error)
	Last() (*model.CaptchaCode, error)
	Find() ([]*model.CaptchaCode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CaptchaCode, err error)
	FindInBatches(result *[]*model.CaptchaCode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CaptchaCode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICaptchaCodeDo
	Assign(attrs ...field.AssignExpr) ICaptchaCodeDo
	Joins(fields ...field.RelationField) ICaptchaCodeDo
	Preload(fields ...field.RelationField) ICaptchaCodeDo
	FirstOrInit() (*model.CaptchaCode, error)
	FirstOrCreate() (*model.CaptchaCode, error)
	FindByPage(offset int, limit int) (result []*model.CaptchaCode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICaptchaCodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c captchaCodeDo) Debug() ICaptchaCodeDo {
	return c.withDO(c.DO.Debug())
}

func (c captchaCodeDo) WithContext(ctx context.Context) ICaptchaCodeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c captchaCodeDo) ReadDB() ICaptchaCodeDo {
	return c.Clauses(dbresolver.Read)
}

func (c captchaCodeDo) WriteDB() ICaptchaCodeDo {
	return c.Clauses(dbresolver.Write)
}

func (c captchaCodeDo) Session(config *gorm.Session) ICaptchaCodeDo {
	return c.withDO(c.DO.Session(config))
}

func (c captchaCodeDo) Clauses(conds ...clause.Expression) ICaptchaCodeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c captchaCodeDo) Returning(value interface{}, columns ...string) ICaptchaCodeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c captchaCodeDo) Not(conds ...gen.Condition) ICaptchaCodeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c captchaCodeDo) Or(conds ...gen.Condition) ICaptchaCodeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c captchaCodeDo) Select(conds ...field.Expr) ICaptchaCodeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c captchaCodeDo) Where(conds ...gen.Condition) ICaptchaCodeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c captchaCodeDo) Order(conds ...field.Expr) ICaptchaCodeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c captchaCodeDo) Distinct(cols ...field.Expr) ICaptchaCodeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c captchaCodeDo) Omit(cols ...field.Expr) ICaptchaCodeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c captchaCodeDo) Join(table schema.Tabler, on ...field.Expr) ICaptchaCodeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c captchaCodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICaptchaCodeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c captchaCodeDo) RightJoin(table schema.Tabler, on ...field.Expr) ICaptchaCodeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c captchaCodeDo) Group(cols ...field.Expr) ICaptchaCodeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c captchaCodeDo) Having(conds ...gen.Condition) ICaptchaCodeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c captchaCodeDo) Limit(limit int) ICaptchaCodeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c captchaCodeDo) Offset(offset int) ICaptchaCodeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c captchaCodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICaptchaCodeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c captchaCodeDo) Unscoped() ICaptchaCodeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c captchaCodeDo) Create(values ...*model.CaptchaCode) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c captchaCodeDo) CreateInBatches(values []*model.CaptchaCode, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c captchaCodeDo) Save(values ...*model.CaptchaCode) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c captchaCodeDo) First() (*model.CaptchaCode, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CaptchaCode), nil
	}
}

func (c captchaCodeDo) Take() (*model.CaptchaCode, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CaptchaCode), nil
	}
}

func (c captchaCodeDo) Last() (*model.CaptchaCode, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CaptchaCode), nil
	}
}

func (c captchaCodeDo) Find() ([]*model.CaptchaCode, error) {
	result, err := c.DO.Find()
	return result.([]*model.CaptchaCode), err
}

func (c captchaCodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CaptchaCode, err error) {
	buf := make([]*model.CaptchaCode, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c captchaCodeDo) FindInBatches(result *[]*model.CaptchaCode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c captchaCodeDo) Attrs(attrs ...field.AssignExpr) ICaptchaCodeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c captchaCodeDo) Assign(attrs ...field.AssignExpr) ICaptchaCodeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c captchaCodeDo) Joins(fields ...field.RelationField) ICaptchaCodeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c captchaCodeDo) Preload(fields ...field.RelationField) ICaptchaCodeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c captchaCodeDo) FirstOrInit() (*model.CaptchaCode, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CaptchaCode), nil
	}
}

func (c captchaCodeDo) FirstOrCreate() (*model.CaptchaCode, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CaptchaCode), nil
	}
}

func (c captchaCodeDo) FindByPage(offset int, limit int) (result []*model.CaptchaCode, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c captchaCodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c captchaCodeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c captchaCodeDo) Delete(models ...*model.CaptchaCode) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *captchaCodeDo) withDO(do gen.Dao) *captchaCodeDo {
	c.DO = *do.(*gen.DO)
	return c
}
