// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin_demo/internal/model"
)

func newMemberUpload(db *gorm.DB, opts ...gen.DOOption) memberUpload {
	_memberUpload := memberUpload{}

	_memberUpload.memberUploadDo.UseDB(db, opts...)
	_memberUpload.memberUploadDo.UseModel(&model.MemberUpload{})

	tableName := _memberUpload.memberUploadDo.TableName()
	_memberUpload.ALL = field.NewAsterisk(tableName)
	_memberUpload.ID = field.NewUint64(tableName, "id")
	_memberUpload.MemberID = field.NewUint64(tableName, "member_id")
	_memberUpload.FileName = field.NewString(tableName, "file_name")
	_memberUpload.SaveFilePath = field.NewString(tableName, "save_file_path")

	_memberUpload.fillFieldMap()

	return _memberUpload
}

type memberUpload struct {
	memberUploadDo

	ALL          field.Asterisk
	ID           field.Uint64
	MemberID     field.Uint64
	FileName     field.String
	SaveFilePath field.String

	fieldMap map[string]field.Expr
}

func (m memberUpload) Table(newTableName string) *memberUpload {
	m.memberUploadDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberUpload) As(alias string) *memberUpload {
	m.memberUploadDo.DO = *(m.memberUploadDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberUpload) updateTableName(table string) *memberUpload {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.MemberID = field.NewUint64(table, "member_id")
	m.FileName = field.NewString(table, "file_name")
	m.SaveFilePath = field.NewString(table, "save_file_path")

	m.fillFieldMap()

	return m
}

func (m *memberUpload) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberUpload) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 4)
	m.fieldMap["id"] = m.ID
	m.fieldMap["member_id"] = m.MemberID
	m.fieldMap["file_name"] = m.FileName
	m.fieldMap["save_file_path"] = m.SaveFilePath
}

func (m memberUpload) clone(db *gorm.DB) memberUpload {
	m.memberUploadDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberUpload) replaceDB(db *gorm.DB) memberUpload {
	m.memberUploadDo.ReplaceDB(db)
	return m
}

type memberUploadDo struct{ gen.DO }

type IMemberUploadDo interface {
	gen.SubQuery
	Debug() IMemberUploadDo
	WithContext(ctx context.Context) IMemberUploadDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberUploadDo
	WriteDB() IMemberUploadDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberUploadDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberUploadDo
	Not(conds ...gen.Condition) IMemberUploadDo
	Or(conds ...gen.Condition) IMemberUploadDo
	Select(conds ...field.Expr) IMemberUploadDo
	Where(conds ...gen.Condition) IMemberUploadDo
	Order(conds ...field.Expr) IMemberUploadDo
	Distinct(cols ...field.Expr) IMemberUploadDo
	Omit(cols ...field.Expr) IMemberUploadDo
	Join(table schema.Tabler, on ...field.Expr) IMemberUploadDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberUploadDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberUploadDo
	Group(cols ...field.Expr) IMemberUploadDo
	Having(conds ...gen.Condition) IMemberUploadDo
	Limit(limit int) IMemberUploadDo
	Offset(offset int) IMemberUploadDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberUploadDo
	Unscoped() IMemberUploadDo
	Create(values ...*model.MemberUpload) error
	CreateInBatches(values []*model.MemberUpload, batchSize int) error
	Save(values ...*model.MemberUpload) error
	First() (*model.MemberUpload, error)
	Take() (*model.MemberUpload, error)
	Last() (*model.MemberUpload, error)
	Find() ([]*model.MemberUpload, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberUpload, err error)
	FindInBatches(result *[]*model.MemberUpload, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MemberUpload) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberUploadDo
	Assign(attrs ...field.AssignExpr) IMemberUploadDo
	Joins(fields ...field.RelationField) IMemberUploadDo
	Preload(fields ...field.RelationField) IMemberUploadDo
	FirstOrInit() (*model.MemberUpload, error)
	FirstOrCreate() (*model.MemberUpload, error)
	FindByPage(offset int, limit int) (result []*model.MemberUpload, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberUploadDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberUploadDo) Debug() IMemberUploadDo {
	return m.withDO(m.DO.Debug())
}

func (m memberUploadDo) WithContext(ctx context.Context) IMemberUploadDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberUploadDo) ReadDB() IMemberUploadDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberUploadDo) WriteDB() IMemberUploadDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberUploadDo) Session(config *gorm.Session) IMemberUploadDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberUploadDo) Clauses(conds ...clause.Expression) IMemberUploadDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberUploadDo) Returning(value interface{}, columns ...string) IMemberUploadDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberUploadDo) Not(conds ...gen.Condition) IMemberUploadDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberUploadDo) Or(conds ...gen.Condition) IMemberUploadDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberUploadDo) Select(conds ...field.Expr) IMemberUploadDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberUploadDo) Where(conds ...gen.Condition) IMemberUploadDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberUploadDo) Order(conds ...field.Expr) IMemberUploadDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberUploadDo) Distinct(cols ...field.Expr) IMemberUploadDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberUploadDo) Omit(cols ...field.Expr) IMemberUploadDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberUploadDo) Join(table schema.Tabler, on ...field.Expr) IMemberUploadDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberUploadDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberUploadDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberUploadDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberUploadDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberUploadDo) Group(cols ...field.Expr) IMemberUploadDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberUploadDo) Having(conds ...gen.Condition) IMemberUploadDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberUploadDo) Limit(limit int) IMemberUploadDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberUploadDo) Offset(offset int) IMemberUploadDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberUploadDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberUploadDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberUploadDo) Unscoped() IMemberUploadDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberUploadDo) Create(values ...*model.MemberUpload) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberUploadDo) CreateInBatches(values []*model.MemberUpload, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberUploadDo) Save(values ...*model.MemberUpload) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberUploadDo) First() (*model.MemberUpload, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberUpload), nil
	}
}

func (m memberUploadDo) Take() (*model.MemberUpload, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberUpload), nil
	}
}

func (m memberUploadDo) Last() (*model.MemberUpload, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberUpload), nil
	}
}

func (m memberUploadDo) Find() ([]*model.MemberUpload, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemberUpload), err
}

func (m memberUploadDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberUpload, err error) {
	buf := make([]*model.MemberUpload, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberUploadDo) FindInBatches(result *[]*model.MemberUpload, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberUploadDo) Attrs(attrs ...field.AssignExpr) IMemberUploadDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberUploadDo) Assign(attrs ...field.AssignExpr) IMemberUploadDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberUploadDo) Joins(fields ...field.RelationField) IMemberUploadDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberUploadDo) Preload(fields ...field.RelationField) IMemberUploadDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberUploadDo) FirstOrInit() (*model.MemberUpload, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberUpload), nil
	}
}

func (m memberUploadDo) FirstOrCreate() (*model.MemberUpload, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberUpload), nil
	}
}

func (m memberUploadDo) FindByPage(offset int, limit int) (result []*model.MemberUpload, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberUploadDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberUploadDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberUploadDo) Delete(models ...*model.MemberUpload) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberUploadDo) withDO(do gen.Dao) *memberUploadDo {
	m.DO = *do.(*gen.DO)
	return m
}
