// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin_demo/internal/model"
)

func newMemberAccount(db *gorm.DB, opts ...gen.DOOption) memberAccount {
	_memberAccount := memberAccount{}

	_memberAccount.memberAccountDo.UseDB(db, opts...)
	_memberAccount.memberAccountDo.UseModel(&model.MemberAccount{})

	tableName := _memberAccount.memberAccountDo.TableName()
	_memberAccount.ALL = field.NewAsterisk(tableName)
	_memberAccount.ID = field.NewUint64(tableName, "id")
	_memberAccount.MemberID = field.NewInt64(tableName, "member_id")
	_memberAccount.Amount = field.NewField(tableName, "amount")
	_memberAccount.AmountType = field.NewInt64(tableName, "amount_type")
	_memberAccount.AmountTime = field.NewInt64(tableName, "amount_time")
	_memberAccount.AmountMemos = field.NewString(tableName, "amount_memos")

	_memberAccount.fillFieldMap()

	return _memberAccount
}

type memberAccount struct {
	memberAccountDo

	ALL         field.Asterisk
	ID          field.Uint64
	MemberID    field.Int64
	Amount      field.Field
	AmountType  field.Int64
	AmountTime  field.Int64
	AmountMemos field.String

	fieldMap map[string]field.Expr
}

func (m memberAccount) Table(newTableName string) *memberAccount {
	m.memberAccountDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberAccount) As(alias string) *memberAccount {
	m.memberAccountDo.DO = *(m.memberAccountDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberAccount) updateTableName(table string) *memberAccount {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.MemberID = field.NewInt64(table, "member_id")
	m.Amount = field.NewField(table, "amount")
	m.AmountType = field.NewInt64(table, "amount_type")
	m.AmountTime = field.NewInt64(table, "amount_time")
	m.AmountMemos = field.NewString(table, "amount_memos")

	m.fillFieldMap()

	return m
}

func (m *memberAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberAccount) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["id"] = m.ID
	m.fieldMap["member_id"] = m.MemberID
	m.fieldMap["amount"] = m.Amount
	m.fieldMap["amount_type"] = m.AmountType
	m.fieldMap["amount_time"] = m.AmountTime
	m.fieldMap["amount_memos"] = m.AmountMemos
}

func (m memberAccount) clone(db *gorm.DB) memberAccount {
	m.memberAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberAccount) replaceDB(db *gorm.DB) memberAccount {
	m.memberAccountDo.ReplaceDB(db)
	return m
}

type memberAccountDo struct{ gen.DO }

type IMemberAccountDo interface {
	gen.SubQuery
	Debug() IMemberAccountDo
	WithContext(ctx context.Context) IMemberAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberAccountDo
	WriteDB() IMemberAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberAccountDo
	Not(conds ...gen.Condition) IMemberAccountDo
	Or(conds ...gen.Condition) IMemberAccountDo
	Select(conds ...field.Expr) IMemberAccountDo
	Where(conds ...gen.Condition) IMemberAccountDo
	Order(conds ...field.Expr) IMemberAccountDo
	Distinct(cols ...field.Expr) IMemberAccountDo
	Omit(cols ...field.Expr) IMemberAccountDo
	Join(table schema.Tabler, on ...field.Expr) IMemberAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberAccountDo
	Group(cols ...field.Expr) IMemberAccountDo
	Having(conds ...gen.Condition) IMemberAccountDo
	Limit(limit int) IMemberAccountDo
	Offset(offset int) IMemberAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberAccountDo
	Unscoped() IMemberAccountDo
	Create(values ...*model.MemberAccount) error
	CreateInBatches(values []*model.MemberAccount, batchSize int) error
	Save(values ...*model.MemberAccount) error
	First() (*model.MemberAccount, error)
	Take() (*model.MemberAccount, error)
	Last() (*model.MemberAccount, error)
	Find() ([]*model.MemberAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberAccount, err error)
	FindInBatches(result *[]*model.MemberAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MemberAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberAccountDo
	Assign(attrs ...field.AssignExpr) IMemberAccountDo
	Joins(fields ...field.RelationField) IMemberAccountDo
	Preload(fields ...field.RelationField) IMemberAccountDo
	FirstOrInit() (*model.MemberAccount, error)
	FirstOrCreate() (*model.MemberAccount, error)
	FindByPage(offset int, limit int) (result []*model.MemberAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberAccountDo) Debug() IMemberAccountDo {
	return m.withDO(m.DO.Debug())
}

func (m memberAccountDo) WithContext(ctx context.Context) IMemberAccountDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberAccountDo) ReadDB() IMemberAccountDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberAccountDo) WriteDB() IMemberAccountDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberAccountDo) Session(config *gorm.Session) IMemberAccountDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberAccountDo) Clauses(conds ...clause.Expression) IMemberAccountDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberAccountDo) Returning(value interface{}, columns ...string) IMemberAccountDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberAccountDo) Not(conds ...gen.Condition) IMemberAccountDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberAccountDo) Or(conds ...gen.Condition) IMemberAccountDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberAccountDo) Select(conds ...field.Expr) IMemberAccountDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberAccountDo) Where(conds ...gen.Condition) IMemberAccountDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberAccountDo) Order(conds ...field.Expr) IMemberAccountDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberAccountDo) Distinct(cols ...field.Expr) IMemberAccountDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberAccountDo) Omit(cols ...field.Expr) IMemberAccountDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberAccountDo) Join(table schema.Tabler, on ...field.Expr) IMemberAccountDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberAccountDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberAccountDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberAccountDo) Group(cols ...field.Expr) IMemberAccountDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberAccountDo) Having(conds ...gen.Condition) IMemberAccountDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberAccountDo) Limit(limit int) IMemberAccountDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberAccountDo) Offset(offset int) IMemberAccountDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberAccountDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberAccountDo) Unscoped() IMemberAccountDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberAccountDo) Create(values ...*model.MemberAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberAccountDo) CreateInBatches(values []*model.MemberAccount, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberAccountDo) Save(values ...*model.MemberAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberAccountDo) First() (*model.MemberAccount, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAccount), nil
	}
}

func (m memberAccountDo) Take() (*model.MemberAccount, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAccount), nil
	}
}

func (m memberAccountDo) Last() (*model.MemberAccount, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAccount), nil
	}
}

func (m memberAccountDo) Find() ([]*model.MemberAccount, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemberAccount), err
}

func (m memberAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberAccount, err error) {
	buf := make([]*model.MemberAccount, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberAccountDo) FindInBatches(result *[]*model.MemberAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberAccountDo) Attrs(attrs ...field.AssignExpr) IMemberAccountDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberAccountDo) Assign(attrs ...field.AssignExpr) IMemberAccountDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberAccountDo) Joins(fields ...field.RelationField) IMemberAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberAccountDo) Preload(fields ...field.RelationField) IMemberAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberAccountDo) FirstOrInit() (*model.MemberAccount, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAccount), nil
	}
}

func (m memberAccountDo) FirstOrCreate() (*model.MemberAccount, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAccount), nil
	}
}

func (m memberAccountDo) FindByPage(offset int, limit int) (result []*model.MemberAccount, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberAccountDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberAccountDo) Delete(models ...*model.MemberAccount) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberAccountDo) withDO(do gen.Dao) *memberAccountDo {
	m.DO = *do.(*gen.DO)
	return m
}
