// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin_demo/internal/model"
)

func newMemberProfile(db *gorm.DB, opts ...gen.DOOption) memberProfile {
	_memberProfile := memberProfile{}

	_memberProfile.memberProfileDo.UseDB(db, opts...)
	_memberProfile.memberProfileDo.UseModel(&model.MemberProfile{})

	tableName := _memberProfile.memberProfileDo.TableName()
	_memberProfile.ALL = field.NewAsterisk(tableName)
	_memberProfile.ID = field.NewUint64(tableName, "id")
	_memberProfile.MemberID = field.NewUint64(tableName, "member_id")
	_memberProfile.AccountBalance = field.NewField(tableName, "account_balance")
	_memberProfile.AvailableBalance = field.NewField(tableName, "available_balance")
	_memberProfile.NonAvailableBalance = field.NewField(tableName, "non_available_balance")
	_memberProfile.TotalSpendBalance = field.NewField(tableName, "total_spend_balance")
	_memberProfile.TotalConsumpeTimes = field.NewInt64(tableName, "total_consumpe_times")
	_memberProfile.NickName = field.NewString(tableName, "nick_name")
	_memberProfile.TrueName = field.NewString(tableName, "true_name")
	_memberProfile.Sex = field.NewInt64(tableName, "sex")
	_memberProfile.Mobile = field.NewString(tableName, "mobile")
	_memberProfile.ProvinceID = field.NewUint64(tableName, "province_id")
	_memberProfile.CityID = field.NewUint64(tableName, "city_id")
	_memberProfile.OpenID = field.NewString(tableName, "open_id")
	_memberProfile.HeadImg = field.NewString(tableName, "head_img")
	_memberProfile.Address = field.NewString(tableName, "address")
	_memberProfile.AreaID = field.NewUint64(tableName, "area_id")
	_memberProfile.Age = field.NewInt64(tableName, "age")
	_memberProfile.Scores = field.NewInt64(tableName, "scores")
	_memberProfile.IsRemindCheckIn = field.NewInt64(tableName, "is_remind_check_in")

	_memberProfile.fillFieldMap()

	return _memberProfile
}

type memberProfile struct {
	memberProfileDo

	ALL                 field.Asterisk
	ID                  field.Uint64
	MemberID            field.Uint64
	AccountBalance      field.Field
	AvailableBalance    field.Field
	NonAvailableBalance field.Field
	TotalSpendBalance   field.Field
	TotalConsumpeTimes  field.Int64
	NickName            field.String
	TrueName            field.String
	Sex                 field.Int64
	Mobile              field.String
	ProvinceID          field.Uint64
	CityID              field.Uint64
	OpenID              field.String
	HeadImg             field.String
	Address             field.String
	AreaID              field.Uint64
	Age                 field.Int64
	Scores              field.Int64
	IsRemindCheckIn     field.Int64

	fieldMap map[string]field.Expr
}

func (m memberProfile) Table(newTableName string) *memberProfile {
	m.memberProfileDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberProfile) As(alias string) *memberProfile {
	m.memberProfileDo.DO = *(m.memberProfileDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberProfile) updateTableName(table string) *memberProfile {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.MemberID = field.NewUint64(table, "member_id")
	m.AccountBalance = field.NewField(table, "account_balance")
	m.AvailableBalance = field.NewField(table, "available_balance")
	m.NonAvailableBalance = field.NewField(table, "non_available_balance")
	m.TotalSpendBalance = field.NewField(table, "total_spend_balance")
	m.TotalConsumpeTimes = field.NewInt64(table, "total_consumpe_times")
	m.NickName = field.NewString(table, "nick_name")
	m.TrueName = field.NewString(table, "true_name")
	m.Sex = field.NewInt64(table, "sex")
	m.Mobile = field.NewString(table, "mobile")
	m.ProvinceID = field.NewUint64(table, "province_id")
	m.CityID = field.NewUint64(table, "city_id")
	m.OpenID = field.NewString(table, "open_id")
	m.HeadImg = field.NewString(table, "head_img")
	m.Address = field.NewString(table, "address")
	m.AreaID = field.NewUint64(table, "area_id")
	m.Age = field.NewInt64(table, "age")
	m.Scores = field.NewInt64(table, "scores")
	m.IsRemindCheckIn = field.NewInt64(table, "is_remind_check_in")

	m.fillFieldMap()

	return m
}

func (m *memberProfile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberProfile) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 20)
	m.fieldMap["id"] = m.ID
	m.fieldMap["member_id"] = m.MemberID
	m.fieldMap["account_balance"] = m.AccountBalance
	m.fieldMap["available_balance"] = m.AvailableBalance
	m.fieldMap["non_available_balance"] = m.NonAvailableBalance
	m.fieldMap["total_spend_balance"] = m.TotalSpendBalance
	m.fieldMap["total_consumpe_times"] = m.TotalConsumpeTimes
	m.fieldMap["nick_name"] = m.NickName
	m.fieldMap["true_name"] = m.TrueName
	m.fieldMap["sex"] = m.Sex
	m.fieldMap["mobile"] = m.Mobile
	m.fieldMap["province_id"] = m.ProvinceID
	m.fieldMap["city_id"] = m.CityID
	m.fieldMap["open_id"] = m.OpenID
	m.fieldMap["head_img"] = m.HeadImg
	m.fieldMap["address"] = m.Address
	m.fieldMap["area_id"] = m.AreaID
	m.fieldMap["age"] = m.Age
	m.fieldMap["scores"] = m.Scores
	m.fieldMap["is_remind_check_in"] = m.IsRemindCheckIn
}

func (m memberProfile) clone(db *gorm.DB) memberProfile {
	m.memberProfileDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberProfile) replaceDB(db *gorm.DB) memberProfile {
	m.memberProfileDo.ReplaceDB(db)
	return m
}

type memberProfileDo struct{ gen.DO }

type IMemberProfileDo interface {
	gen.SubQuery
	Debug() IMemberProfileDo
	WithContext(ctx context.Context) IMemberProfileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberProfileDo
	WriteDB() IMemberProfileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberProfileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberProfileDo
	Not(conds ...gen.Condition) IMemberProfileDo
	Or(conds ...gen.Condition) IMemberProfileDo
	Select(conds ...field.Expr) IMemberProfileDo
	Where(conds ...gen.Condition) IMemberProfileDo
	Order(conds ...field.Expr) IMemberProfileDo
	Distinct(cols ...field.Expr) IMemberProfileDo
	Omit(cols ...field.Expr) IMemberProfileDo
	Join(table schema.Tabler, on ...field.Expr) IMemberProfileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberProfileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberProfileDo
	Group(cols ...field.Expr) IMemberProfileDo
	Having(conds ...gen.Condition) IMemberProfileDo
	Limit(limit int) IMemberProfileDo
	Offset(offset int) IMemberProfileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberProfileDo
	Unscoped() IMemberProfileDo
	Create(values ...*model.MemberProfile) error
	CreateInBatches(values []*model.MemberProfile, batchSize int) error
	Save(values ...*model.MemberProfile) error
	First() (*model.MemberProfile, error)
	Take() (*model.MemberProfile, error)
	Last() (*model.MemberProfile, error)
	Find() ([]*model.MemberProfile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberProfile, err error)
	FindInBatches(result *[]*model.MemberProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MemberProfile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberProfileDo
	Assign(attrs ...field.AssignExpr) IMemberProfileDo
	Joins(fields ...field.RelationField) IMemberProfileDo
	Preload(fields ...field.RelationField) IMemberProfileDo
	FirstOrInit() (*model.MemberProfile, error)
	FirstOrCreate() (*model.MemberProfile, error)
	FindByPage(offset int, limit int) (result []*model.MemberProfile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberProfileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberProfileDo) Debug() IMemberProfileDo {
	return m.withDO(m.DO.Debug())
}

func (m memberProfileDo) WithContext(ctx context.Context) IMemberProfileDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberProfileDo) ReadDB() IMemberProfileDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberProfileDo) WriteDB() IMemberProfileDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberProfileDo) Session(config *gorm.Session) IMemberProfileDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberProfileDo) Clauses(conds ...clause.Expression) IMemberProfileDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberProfileDo) Returning(value interface{}, columns ...string) IMemberProfileDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberProfileDo) Not(conds ...gen.Condition) IMemberProfileDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberProfileDo) Or(conds ...gen.Condition) IMemberProfileDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberProfileDo) Select(conds ...field.Expr) IMemberProfileDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberProfileDo) Where(conds ...gen.Condition) IMemberProfileDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberProfileDo) Order(conds ...field.Expr) IMemberProfileDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberProfileDo) Distinct(cols ...field.Expr) IMemberProfileDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberProfileDo) Omit(cols ...field.Expr) IMemberProfileDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberProfileDo) Join(table schema.Tabler, on ...field.Expr) IMemberProfileDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberProfileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberProfileDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberProfileDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberProfileDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberProfileDo) Group(cols ...field.Expr) IMemberProfileDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberProfileDo) Having(conds ...gen.Condition) IMemberProfileDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberProfileDo) Limit(limit int) IMemberProfileDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberProfileDo) Offset(offset int) IMemberProfileDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberProfileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberProfileDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberProfileDo) Unscoped() IMemberProfileDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberProfileDo) Create(values ...*model.MemberProfile) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberProfileDo) CreateInBatches(values []*model.MemberProfile, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberProfileDo) Save(values ...*model.MemberProfile) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberProfileDo) First() (*model.MemberProfile, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberProfile), nil
	}
}

func (m memberProfileDo) Take() (*model.MemberProfile, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberProfile), nil
	}
}

func (m memberProfileDo) Last() (*model.MemberProfile, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberProfile), nil
	}
}

func (m memberProfileDo) Find() ([]*model.MemberProfile, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemberProfile), err
}

func (m memberProfileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberProfile, err error) {
	buf := make([]*model.MemberProfile, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberProfileDo) FindInBatches(result *[]*model.MemberProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberProfileDo) Attrs(attrs ...field.AssignExpr) IMemberProfileDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberProfileDo) Assign(attrs ...field.AssignExpr) IMemberProfileDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberProfileDo) Joins(fields ...field.RelationField) IMemberProfileDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberProfileDo) Preload(fields ...field.RelationField) IMemberProfileDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberProfileDo) FirstOrInit() (*model.MemberProfile, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberProfile), nil
	}
}

func (m memberProfileDo) FirstOrCreate() (*model.MemberProfile, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberProfile), nil
	}
}

func (m memberProfileDo) FindByPage(offset int, limit int) (result []*model.MemberProfile, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberProfileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberProfileDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberProfileDo) Delete(models ...*model.MemberProfile) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberProfileDo) withDO(do gen.Dao) *memberProfileDo {
	m.DO = *do.(*gen.DO)
	return m
}
