// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin_demo/internal/model"
)

func newMemberAddress(db *gorm.DB, opts ...gen.DOOption) memberAddress {
	_memberAddress := memberAddress{}

	_memberAddress.memberAddressDo.UseDB(db, opts...)
	_memberAddress.memberAddressDo.UseModel(&model.MemberAddress{})

	tableName := _memberAddress.memberAddressDo.TableName()
	_memberAddress.ALL = field.NewAsterisk(tableName)
	_memberAddress.ID = field.NewInt64(tableName, "id")
	_memberAddress.MemberID = field.NewUint64(tableName, "member_id")
	_memberAddress.Address = field.NewString(tableName, "address")
	_memberAddress.Tel = field.NewString(tableName, "tel")
	_memberAddress.IsDefault = field.NewInt64(tableName, "is_default")
	_memberAddress.CreatedAt = field.NewInt64(tableName, "created_at")
	_memberAddress.ConsigneeName = field.NewString(tableName, "consignee_name")
	_memberAddress.Post = field.NewString(tableName, "post")
	_memberAddress.ProvinceID = field.NewInt64(tableName, "province_id")
	_memberAddress.CityID = field.NewInt64(tableName, "city_id")
	_memberAddress.AreaID = field.NewInt64(tableName, "area_id")
	_memberAddress.DeletedAt = field.NewField(tableName, "deleted_at")

	_memberAddress.fillFieldMap()

	return _memberAddress
}

// memberAddress 用户常用地址表
type memberAddress struct {
	memberAddressDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键ID
	MemberID      field.Uint64 //  用户id唯一标识
	Address       field.String // 收货地址
	Tel           field.String // 收货人手机号码
	IsDefault     field.Int64  // 是否默认
	CreatedAt     field.Int64  // 创建时间
	ConsigneeName field.String // 收货人姓名
	Post          field.String // 邮编
	ProvinceID    field.Int64  // 省份名称
	CityID        field.Int64  // 城市名称
	AreaID        field.Int64  // 区县名称
	DeletedAt     field.Field

	fieldMap map[string]field.Expr
}

func (m memberAddress) Table(newTableName string) *memberAddress {
	m.memberAddressDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberAddress) As(alias string) *memberAddress {
	m.memberAddressDo.DO = *(m.memberAddressDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberAddress) updateTableName(table string) *memberAddress {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MemberID = field.NewUint64(table, "member_id")
	m.Address = field.NewString(table, "address")
	m.Tel = field.NewString(table, "tel")
	m.IsDefault = field.NewInt64(table, "is_default")
	m.CreatedAt = field.NewInt64(table, "created_at")
	m.ConsigneeName = field.NewString(table, "consignee_name")
	m.Post = field.NewString(table, "post")
	m.ProvinceID = field.NewInt64(table, "province_id")
	m.CityID = field.NewInt64(table, "city_id")
	m.AreaID = field.NewInt64(table, "area_id")
	m.DeletedAt = field.NewField(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *memberAddress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberAddress) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["member_id"] = m.MemberID
	m.fieldMap["address"] = m.Address
	m.fieldMap["tel"] = m.Tel
	m.fieldMap["is_default"] = m.IsDefault
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["consignee_name"] = m.ConsigneeName
	m.fieldMap["post"] = m.Post
	m.fieldMap["province_id"] = m.ProvinceID
	m.fieldMap["city_id"] = m.CityID
	m.fieldMap["area_id"] = m.AreaID
	m.fieldMap["deleted_at"] = m.DeletedAt
}

func (m memberAddress) clone(db *gorm.DB) memberAddress {
	m.memberAddressDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberAddress) replaceDB(db *gorm.DB) memberAddress {
	m.memberAddressDo.ReplaceDB(db)
	return m
}

type memberAddressDo struct{ gen.DO }

type IMemberAddressDo interface {
	gen.SubQuery
	Debug() IMemberAddressDo
	WithContext(ctx context.Context) IMemberAddressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberAddressDo
	WriteDB() IMemberAddressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberAddressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberAddressDo
	Not(conds ...gen.Condition) IMemberAddressDo
	Or(conds ...gen.Condition) IMemberAddressDo
	Select(conds ...field.Expr) IMemberAddressDo
	Where(conds ...gen.Condition) IMemberAddressDo
	Order(conds ...field.Expr) IMemberAddressDo
	Distinct(cols ...field.Expr) IMemberAddressDo
	Omit(cols ...field.Expr) IMemberAddressDo
	Join(table schema.Tabler, on ...field.Expr) IMemberAddressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberAddressDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberAddressDo
	Group(cols ...field.Expr) IMemberAddressDo
	Having(conds ...gen.Condition) IMemberAddressDo
	Limit(limit int) IMemberAddressDo
	Offset(offset int) IMemberAddressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberAddressDo
	Unscoped() IMemberAddressDo
	Create(values ...*model.MemberAddress) error
	CreateInBatches(values []*model.MemberAddress, batchSize int) error
	Save(values ...*model.MemberAddress) error
	First() (*model.MemberAddress, error)
	Take() (*model.MemberAddress, error)
	Last() (*model.MemberAddress, error)
	Find() ([]*model.MemberAddress, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberAddress, err error)
	FindInBatches(result *[]*model.MemberAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MemberAddress) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberAddressDo
	Assign(attrs ...field.AssignExpr) IMemberAddressDo
	Joins(fields ...field.RelationField) IMemberAddressDo
	Preload(fields ...field.RelationField) IMemberAddressDo
	FirstOrInit() (*model.MemberAddress, error)
	FirstOrCreate() (*model.MemberAddress, error)
	FindByPage(offset int, limit int) (result []*model.MemberAddress, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberAddressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberAddressDo) Debug() IMemberAddressDo {
	return m.withDO(m.DO.Debug())
}

func (m memberAddressDo) WithContext(ctx context.Context) IMemberAddressDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberAddressDo) ReadDB() IMemberAddressDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberAddressDo) WriteDB() IMemberAddressDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberAddressDo) Session(config *gorm.Session) IMemberAddressDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberAddressDo) Clauses(conds ...clause.Expression) IMemberAddressDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberAddressDo) Returning(value interface{}, columns ...string) IMemberAddressDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberAddressDo) Not(conds ...gen.Condition) IMemberAddressDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberAddressDo) Or(conds ...gen.Condition) IMemberAddressDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberAddressDo) Select(conds ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberAddressDo) Where(conds ...gen.Condition) IMemberAddressDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberAddressDo) Order(conds ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberAddressDo) Distinct(cols ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberAddressDo) Omit(cols ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberAddressDo) Join(table schema.Tabler, on ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberAddressDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberAddressDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberAddressDo) Group(cols ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberAddressDo) Having(conds ...gen.Condition) IMemberAddressDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberAddressDo) Limit(limit int) IMemberAddressDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberAddressDo) Offset(offset int) IMemberAddressDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberAddressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberAddressDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberAddressDo) Unscoped() IMemberAddressDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberAddressDo) Create(values ...*model.MemberAddress) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberAddressDo) CreateInBatches(values []*model.MemberAddress, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberAddressDo) Save(values ...*model.MemberAddress) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberAddressDo) First() (*model.MemberAddress, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAddress), nil
	}
}

func (m memberAddressDo) Take() (*model.MemberAddress, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAddress), nil
	}
}

func (m memberAddressDo) Last() (*model.MemberAddress, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAddress), nil
	}
}

func (m memberAddressDo) Find() ([]*model.MemberAddress, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemberAddress), err
}

func (m memberAddressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemberAddress, err error) {
	buf := make([]*model.MemberAddress, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberAddressDo) FindInBatches(result *[]*model.MemberAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberAddressDo) Attrs(attrs ...field.AssignExpr) IMemberAddressDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberAddressDo) Assign(attrs ...field.AssignExpr) IMemberAddressDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberAddressDo) Joins(fields ...field.RelationField) IMemberAddressDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberAddressDo) Preload(fields ...field.RelationField) IMemberAddressDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberAddressDo) FirstOrInit() (*model.MemberAddress, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAddress), nil
	}
}

func (m memberAddressDo) FirstOrCreate() (*model.MemberAddress, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemberAddress), nil
	}
}

func (m memberAddressDo) FindByPage(offset int, limit int) (result []*model.MemberAddress, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberAddressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberAddressDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberAddressDo) Delete(models ...*model.MemberAddress) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberAddressDo) withDO(do gen.Dao) *memberAddressDo {
	m.DO = *do.(*gen.DO)
	return m
}
