// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin_demo/internal/model"
)

func newMember(db *gorm.DB, opts ...gen.DOOption) member {
	_member := member{}

	_member.memberDo.UseDB(db, opts...)
	_member.memberDo.UseModel(&model.Member{})

	tableName := _member.memberDo.TableName()
	_member.ALL = field.NewAsterisk(tableName)
	_member.ID = field.NewUint64(tableName, "id")
	_member.MemberName = field.NewString(tableName, "member_name")
	_member.MemberPass = field.NewString(tableName, "member_pass")
	_member.Mobile = field.NewString(tableName, "mobile")
	_member.Email = field.NewString(tableName, "email")
	_member.ParentID = field.NewInt64(tableName, "parent_id")
	_member.CreatedAt = field.NewInt64(tableName, "created_at")
	_member.CreatedIP = field.NewString(tableName, "created_ip")
	_member.LoginTime = field.NewInt64(tableName, "login_time")
	_member.LoginIP = field.NewString(tableName, "login_ip")
	_member.LoginTimes = field.NewInt64(tableName, "login_times")
	_member.Salt = field.NewString(tableName, "salt")
	_member.Status = field.NewUint64(tableName, "status")
	_member.OpenID = field.NewString(tableName, "open_id")
	_member.UnionID = field.NewString(tableName, "union_id")
	_member.RegType = field.NewUint64(tableName, "reg_type")
	_member.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_member.MemberTypeID = field.NewInt64(tableName, "member_type_id")
	_member.InviteCode = field.NewString(tableName, "invite_code")

	_member.fillFieldMap()

	return _member
}

type member struct {
	memberDo

	ALL          field.Asterisk
	ID           field.Uint64
	MemberName   field.String // 用户名字
	MemberPass   field.String // 密码
	Mobile       field.String // 手机号码
	Email        field.String // 邮箱
	ParentID     field.Int64
	CreatedAt    field.Int64  // 创建时间
	CreatedIP    field.String // 创建IP
	LoginTime    field.Int64  // 上次登陆时间
	LoginIP      field.String // 上次登陆IP
	LoginTimes   field.Int64  // 总登陆次数
	Salt         field.String // 用户密码salt
	Status       field.Uint64 // 会员状态 1 正常 0 已禁用
	OpenID       field.String
	UnionID      field.String
	RegType      field.Uint64 // 注册类型 1 普通 2 手机号码密码注册 3 微信小程序注册 4 手机号码验证码注册
	UpdatedAt    field.Int64
	MemberTypeID field.Int64 // 用户等级
	InviteCode   field.String

	fieldMap map[string]field.Expr
}

func (m member) Table(newTableName string) *member {
	m.memberDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m member) As(alias string) *member {
	m.memberDo.DO = *(m.memberDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *member) updateTableName(table string) *member {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.MemberName = field.NewString(table, "member_name")
	m.MemberPass = field.NewString(table, "member_pass")
	m.Mobile = field.NewString(table, "mobile")
	m.Email = field.NewString(table, "email")
	m.ParentID = field.NewInt64(table, "parent_id")
	m.CreatedAt = field.NewInt64(table, "created_at")
	m.CreatedIP = field.NewString(table, "created_ip")
	m.LoginTime = field.NewInt64(table, "login_time")
	m.LoginIP = field.NewString(table, "login_ip")
	m.LoginTimes = field.NewInt64(table, "login_times")
	m.Salt = field.NewString(table, "salt")
	m.Status = field.NewUint64(table, "status")
	m.OpenID = field.NewString(table, "open_id")
	m.UnionID = field.NewString(table, "union_id")
	m.RegType = field.NewUint64(table, "reg_type")
	m.UpdatedAt = field.NewInt64(table, "updated_at")
	m.MemberTypeID = field.NewInt64(table, "member_type_id")
	m.InviteCode = field.NewString(table, "invite_code")

	m.fillFieldMap()

	return m
}

func (m *member) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *member) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 19)
	m.fieldMap["id"] = m.ID
	m.fieldMap["member_name"] = m.MemberName
	m.fieldMap["member_pass"] = m.MemberPass
	m.fieldMap["mobile"] = m.Mobile
	m.fieldMap["email"] = m.Email
	m.fieldMap["parent_id"] = m.ParentID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["created_ip"] = m.CreatedIP
	m.fieldMap["login_time"] = m.LoginTime
	m.fieldMap["login_ip"] = m.LoginIP
	m.fieldMap["login_times"] = m.LoginTimes
	m.fieldMap["salt"] = m.Salt
	m.fieldMap["status"] = m.Status
	m.fieldMap["open_id"] = m.OpenID
	m.fieldMap["union_id"] = m.UnionID
	m.fieldMap["reg_type"] = m.RegType
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["member_type_id"] = m.MemberTypeID
	m.fieldMap["invite_code"] = m.InviteCode
}

func (m member) clone(db *gorm.DB) member {
	m.memberDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m member) replaceDB(db *gorm.DB) member {
	m.memberDo.ReplaceDB(db)
	return m
}

type memberDo struct{ gen.DO }

type IMemberDo interface {
	gen.SubQuery
	Debug() IMemberDo
	WithContext(ctx context.Context) IMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberDo
	WriteDB() IMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberDo
	Not(conds ...gen.Condition) IMemberDo
	Or(conds ...gen.Condition) IMemberDo
	Select(conds ...field.Expr) IMemberDo
	Where(conds ...gen.Condition) IMemberDo
	Order(conds ...field.Expr) IMemberDo
	Distinct(cols ...field.Expr) IMemberDo
	Omit(cols ...field.Expr) IMemberDo
	Join(table schema.Tabler, on ...field.Expr) IMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberDo
	Group(cols ...field.Expr) IMemberDo
	Having(conds ...gen.Condition) IMemberDo
	Limit(limit int) IMemberDo
	Offset(offset int) IMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberDo
	Unscoped() IMemberDo
	Create(values ...*model.Member) error
	CreateInBatches(values []*model.Member, batchSize int) error
	Save(values ...*model.Member) error
	First() (*model.Member, error)
	Take() (*model.Member, error)
	Last() (*model.Member, error)
	Find() ([]*model.Member, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Member, err error)
	FindInBatches(result *[]*model.Member, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Member) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberDo
	Assign(attrs ...field.AssignExpr) IMemberDo
	Joins(fields ...field.RelationField) IMemberDo
	Preload(fields ...field.RelationField) IMemberDo
	FirstOrInit() (*model.Member, error)
	FirstOrCreate() (*model.Member, error)
	FindByPage(offset int, limit int) (result []*model.Member, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberDo) Debug() IMemberDo {
	return m.withDO(m.DO.Debug())
}

func (m memberDo) WithContext(ctx context.Context) IMemberDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberDo) ReadDB() IMemberDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberDo) WriteDB() IMemberDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberDo) Session(config *gorm.Session) IMemberDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberDo) Clauses(conds ...clause.Expression) IMemberDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberDo) Returning(value interface{}, columns ...string) IMemberDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberDo) Not(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberDo) Or(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberDo) Select(conds ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberDo) Where(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberDo) Order(conds ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberDo) Distinct(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberDo) Omit(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberDo) Join(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberDo) Group(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberDo) Having(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberDo) Limit(limit int) IMemberDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberDo) Offset(offset int) IMemberDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberDo) Unscoped() IMemberDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberDo) Create(values ...*model.Member) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberDo) CreateInBatches(values []*model.Member, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberDo) Save(values ...*model.Member) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberDo) First() (*model.Member, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) Take() (*model.Member, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) Last() (*model.Member, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) Find() ([]*model.Member, error) {
	result, err := m.DO.Find()
	return result.([]*model.Member), err
}

func (m memberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Member, err error) {
	buf := make([]*model.Member, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberDo) FindInBatches(result *[]*model.Member, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberDo) Attrs(attrs ...field.AssignExpr) IMemberDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberDo) Assign(attrs ...field.AssignExpr) IMemberDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberDo) Joins(fields ...field.RelationField) IMemberDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberDo) Preload(fields ...field.RelationField) IMemberDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberDo) FirstOrInit() (*model.Member, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) FirstOrCreate() (*model.Member, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Member), nil
	}
}

func (m memberDo) FindByPage(offset int, limit int) (result []*model.Member, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberDo) Delete(models ...*model.Member) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberDo) withDO(do gen.Dao) *memberDo {
	m.DO = *do.(*gen.DO)
	return m
}
