// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCaptchaCode = "captcha_code"

// CaptchaCode mapped from table <captcha_code>
type CaptchaCode struct {
	ID             uint64 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	CaptchaType    int64  `gorm:"column:captcha_type;type:tinyint;not null;default:1;comment:1 mobile 2 email" json:"captcha_type"` // 1 mobile 2 email
	CaptchaAccount string `gorm:"column:captcha_account;type:varchar(55);not null" json:"captcha_account"`
	CaptchaCode    string `gorm:"column:captcha_code;type:varchar(6);not null" json:"captcha_code"`
	IsExpired      uint64 `gorm:"column:is_expired;type:tinyint unsigned;not null;default:1;comment:1：未过期  2：已失效" json:"is_expired"` // 1：未过期  2：已失效
	IsUsed         int64  `gorm:"column:is_used;type:tinyint;not null;comment:1：已使用  0：未使用" json:"is_used"`                          // 1：已使用  0：未使用
	ExpiredTime    int64  `gorm:"column:expired_time;type:int;not null" json:"expired_time"`
	CreatedAt      uint64 `gorm:"column:created_at;type:int;type:unsigned;not null;autoCreateTime" json:"created_at"`
	UpdatedAt      uint64 `gorm:"column:updated_at;type:int;type:unsigned;not null;autoUpdateTime" json:"updated_at"`
}

// TableName CaptchaCode's table name
func (*CaptchaCode) TableName() string {
	return TableNameCaptchaCode
}
