// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemberUpload = "member_upload"

// MemberUpload mapped from table <member_upload>
type MemberUpload struct {
	ID           uint64 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberID     uint64 `gorm:"column:member_id;type:int(10) unsigned zerofill;not null" json:"member_id"`
	FileName     string `gorm:"column:file_name;type:varchar(300);not null" json:"file_name"`
	SaveFilePath string `gorm:"column:save_file_path;type:varchar(800);not null" json:"save_file_path"`
}

// TableName MemberUpload's table name
func (*MemberUpload) TableName() string {
	return TableNameMemberUpload
}
