// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMember = "ps_member"

// Member mapped from table <ps_member>
type Member struct {
	ID           uint64 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberName   string `gorm:"column:member_name;type:varchar(35);not null;index:member_name,priority:1;comment:用户名字" json:"member_name"` // 用户名字
	MemberPass   string `gorm:"column:member_pass;type:varchar(100);not null;comment:密码" json:"member_pass"`                               // 密码
	Mobile       string `gorm:"column:mobile;type:varchar(11);not null;uniqueIndex:mobile,priority:1;comment:手机号码" json:"mobile"`          // 手机号码
	Email        string `gorm:"column:email;type:varchar(100);index:email,priority:1;comment:邮箱" json:"email"`                             // 邮箱
	ParentID     int64  `gorm:"column:parent_id;type:int" json:"parent_id"`
	CreatedAt    int64  `gorm:"column:created_at;type:int;type:unsigned;not null;autoCreateTime;comment:创建时间" json:"created_at"` // 创建时间
	CreatedIP    string `gorm:"column:created_ip;type:varchar(20);comment:创建IP" json:"created_ip"`                               // 创建IP
	LoginTime    int64  `gorm:"column:login_time;type:int;comment:上次登陆时间" json:"login_time"`                                     // 上次登陆时间
	LoginIP      string `gorm:"column:login_ip;type:varchar(20);comment:上次登陆IP" json:"login_ip"`                                 // 上次登陆IP
	LoginTimes   int64  `gorm:"column:login_times;type:int;comment:总登陆次数" json:"login_times"`                                    // 总登陆次数
	Salt         string `gorm:"column:salt;type:char(32);comment:用户密码salt" json:"salt"`                                          // 用户密码salt
	Status       uint64 `gorm:"column:status;type:int unsigned;not null;default:1;comment:会员状态 1 正常 0 已禁用" json:"status"`        // 会员状态 1 正常 0 已禁用
	OpenID       string `gorm:"column:open_id;type:varchar(100);index:open_id,priority:1" json:"open_id"`
	UnionID      string `gorm:"column:union_id;type:varchar(100)" json:"union_id"`
	RegType      uint64 `gorm:"column:reg_type;type:tinyint unsigned;default:1;comment:注册类型 1 普通 2 手机号码密码注册 3 微信小程序注册 4 手机号码验证码注册" json:"reg_type"` // 注册类型 1 普通 2 手机号码密码注册 3 微信小程序注册 4 手机号码验证码注册
	UpdatedAt    int64  `gorm:"column:updated_at;type:int;type:unsigned;not null;autoUpdateTime" json:"updated_at"`
	MemberTypeID int64  `gorm:"column:member_type_id;type:int;default:1;comment:用户等级" json:"member_type_id"` // 用户等级
	InviteCode   string `gorm:"column:invite_code;type:varchar(10)" json:"invite_code"`
}

// TableName Member's table name
func (*Member) TableName() string {
	return TableNameMember
}
