// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameMemberAccount = "ps_member_account"

// MemberAccount mapped from table <ps_member_account>
type MemberAccount struct {
	ID          uint64          `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberID    int64           `gorm:"column:member_id;type:int;not null" json:"member_id"`
	Amount      decimal.Decimal `gorm:"column:amount;type:decimal(10,3);not null" json:"amount"`
	AmountType  int64           `gorm:"column:amount_type;type:tinyint;not null;default:1" json:"amount_type"`
	AmountTime  int64           `gorm:"column:amount_time;type:int;not null" json:"amount_time"`
	AmountMemos string          `gorm:"column:amount_memos;type:varchar(100);not null" json:"amount_memos"`
}

// TableName MemberAccount's table name
func (*MemberAccount) TableName() string {
	return TableNameMemberAccount
}
