// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameMemberProfile = "ps_member_profile"

// MemberProfile mapped from table <ps_member_profile>
type MemberProfile struct {
	ID                  uint64          `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberID            uint64          `gorm:"column:member_id;type:int unsigned;not null" json:"member_id"`
	AccountBalance      decimal.Decimal `gorm:"column:account_balance;type:decimal(10,3);default:0.000" json:"account_balance"`
	AvailableBalance    decimal.Decimal `gorm:"column:available_balance;type:decimal(10,3);default:0.000" json:"available_balance"`
	NonAvailableBalance decimal.Decimal `gorm:"column:non_available_balance;type:decimal(10,3);default:0.000" json:"non_available_balance"`
	TotalSpendBalance   decimal.Decimal `gorm:"column:total_spend_balance;type:decimal(10,3);default:0.000" json:"total_spend_balance"`
	TotalConsumpeTimes  int64           `gorm:"column:total_consumpe_times;type:int" json:"total_consumpe_times"`
	NickName            string          `gorm:"column:nick_name;type:varchar(255)" json:"nick_name"`
	TrueName            string          `gorm:"column:true_name;type:varchar(255)" json:"true_name"`
	Sex                 int64           `gorm:"column:sex;type:tinyint" json:"sex"`
	Mobile              string          `gorm:"column:mobile;type:varchar(255)" json:"mobile"`
	ProvinceID          uint64          `gorm:"column:province_id;type:int unsigned" json:"province_id"`
	CityID              uint64          `gorm:"column:city_id;type:int unsigned" json:"city_id"`
	OpenID              string          `gorm:"column:open_id;type:varchar(100)" json:"open_id"`
	HeadImg             string          `gorm:"column:head_img;type:varchar(255)" json:"head_img"`
	Address             string          `gorm:"column:address;type:varchar(255)" json:"address"`
	AreaID              uint64          `gorm:"column:area_id;type:int unsigned" json:"area_id"`
	Age                 int64           `gorm:"column:age;type:int;default:1" json:"age"`
	Scores              int64           `gorm:"column:scores;type:int" json:"scores"`
	IsRemindCheckIn     int64           `gorm:"column:is_remind_check_in;type:tinyint" json:"is_remind_check_in"`
}

// TableName MemberProfile's table name
func (*MemberProfile) TableName() string {
	return TableNameMemberProfile
}
