// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameMemberAddress = "ps_member_address"

// MemberAddress 用户常用地址表
type MemberAddress struct {
	ID            int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                         // 主键ID
	MemberID      uint64                `gorm:"column:member_id;type:int unsigned;not null;comment: 用户id唯一标识" json:"member_id"`                  //  用户id唯一标识
	Address       string                `gorm:"column:address;type:varchar(200);not null;comment:收货地址" json:"address"`                           // 收货地址
	Tel           string                `gorm:"column:tel;type:varchar(15);not null;comment:收货人手机号码" json:"tel"`                                 // 收货人手机号码
	IsDefault     int64                 `gorm:"column:is_default;type:tinyint;not null;comment:是否默认" json:"is_default"`                          // 是否默认
	CreatedAt     int64                 `gorm:"column:created_at;type:int;type:unsigned;not null;autoCreateTime;comment:创建时间" json:"created_at"` // 创建时间
	ConsigneeName string                `gorm:"column:consignee_name;type:varchar(20);not null;comment:收货人姓名" json:"consignee_name"`             // 收货人姓名
	Post          string                `gorm:"column:post;type:varchar(8);not null;default:610000;comment:邮编" json:"post"`                      // 邮编
	ProvinceID    int64                 `gorm:"column:province_id;type:int;not null;comment:省份名称" json:"province_id"`                            // 省份名称
	CityID        int64                 `gorm:"column:city_id;type:int;not null;comment:城市名称" json:"city_id"`                                    // 城市名称
	AreaID        int64                 `gorm:"column:area_id;type:int;not null;comment:区县名称" json:"area_id"`                                    // 区县名称
	DeletedAt     soft_delete.DeletedAt `gorm:"column:deleted_at;type:int;not null;softDelete:flag" json:"deleted_at"`
}

// TableName MemberAddress's table name
func (*MemberAddress) TableName() string {
	return TableNameMemberAddress
}
